version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo Installing soure NPM dependencies...
      - npm install
  build:
    commands:
      - echo build started on 'date'
      - echo building the Node.js application...
      - npm run  build
  post_build:
    commands:
      - echo build completed on 'date'
      - mkdir deploy
      - cp -r dist deploy/dist
      - mv appspec.yaml appspec.yml
      - cp appspec.yml deploy/
      - cp -r scripts deploy/
      - chmod +x deploy/scripts/restartnginx.sh
      - chmod +x deploy/scripts/appstop.sh
artifacts:
  files:
     - '**/*'
  base-directory: deploy
  name: frontend-build