version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo Installing soure NPM dependencies...
      - npm install
  build:
    commands:
      - echo build started on 'date'
      - echo building the Node.js application...
      - npm run  build
  post_build:
    commands:
      - echo build completed on 'date'
      - mkdir deplay
      - cp -r dist deplay/dist
      - mv appspec.yaml appspec.yml
      - cp appspec.yml deplay/
      - cp -r scripts deplay/
      - chmod +x deplay/scripts/restartNginx.sh
      - chmod +x deplay/scripts/aapstop.sh
artifacts:
  files:
     - '**/*'
  base-directory: 'dist'